### ISSUE TITLE
in renaming cases, if node has > 1 identifier child, all get renamed

### ISSUE THREAD

**Issue by dariajung** [angular/ts-minify#41]
For instance, with `PropertyAssignment`s, we just want to rename `name`. 

```js
 interface PropertyAssignment extends ObjectLiteralElement {
        _propertyAssignmentBrand: any;
        name: DeclarationName;
        questionToken?: Node;
        initializer: Expression;
    }
```
original:
```js
function getFileAndName(): { fileName: string, qname: string } {
    var fileName = 'hello';
    var blah = 'world';
    return { fileName, qname: blah };
}
```

renaming: 

```js
function getFileAndName(): { $: string, _: string } {
    var fileName = 'hello';
    var blah = 'world';
    return { fileName, _: a };
}
```

`blah` gets renamed to `a` even though it is not a property name because it is an identifier node.

in a PropertyAssignment:
initializer: `Expression`; but `Expression` might be an `Identifier`

Possible fix: Check if `(<any>node).name` exists, if so, compare to `child`. If `node.name === child`, we can rename?

**Comment by dariajung** [comment]
Proposed fix:

```js
let hasName = (<any>node).name;
      if (renameIdent && child.kind === ts.SyntaxKind.Identifier && hasName === child) {
        childText = this._renameIdent(child);
      } else {
        childText = this.visit(child);
      }
```

**Comment by rkirov** [comment]
As discussed object literal destructuring cannot be handled well, because it contains a property declaration or access (things we rename) and a local variable expression (something we leave to uglifyJS).
```
var {a} = foo;
```
is sugar for
```
var a = foo.a;
```
which should be renamed to 
```
var a = foo.$
```
but there is no way to do that while keeping the sugar.

Similarly for property declaration ```{a}``` is sugar for ```{a: a}``` and we rename that to ```{$: a}```. For now I suggest we detect these and throw an error.
